name: CI/CD

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]
 
concurrency:
  group: ci-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: 'Install dependencies'
        run: yarn install

      - name: 'Lint'
        run: yarn lint --quiet

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 'Install dependencies'
        run: yarn install

      - name: 'Build'
        run: yarn build
        env:
          SENTRY_SKIP_AUTO_RELEASE: true

      - name: 'Test'
        run: yarn test
        
